color_format = "3"
humidity_min = 8
temperature_max = 65
sharp_movement_threshold = 25000
humidity_max = 77
enable_mq2 = false
enable_flame = true
enable_mq9 = true
enable_dht = true
date_format = "2"
time_format = "2"
enable_buzzer = false
notification = "on"
email = "dsada@dasd.ru"
enable_led = false
