temperature_max = "54"
humidity_max = "5"
sharp_movement_threshold = 10000
enable_flame = false
enable_dht = true
enable_accel = true
sharp_movement_threshold = 50000
enable_flame = true
enable_mq2 = false
enable_mq9 = false
humidity_min = 0
humidity_max = 100
temperature_max = 100
email = "test@gmail.com"
notification = "on"
email = "myemail@yahoo.org"
