temperature_max = "54"
humidity_max = "95"
sharp_movement_threshold = 10000
enable_flame = false
enable_dht = true
enable_mq9 = false
enable_mq2 = false
humidity_min = "30"
color_format = "1"
date_format = "2"
time_format = "1"
enable_led = "false"
enable_buzzer = "false"
notification = "on"
email = "alex@gmail.ru"
