temperature_max = "54"
humidity_max = "5"
sharp_movement_threshold = 30000
enable_flame = false
enable_dht = true
enable_mq9 = true
enable_mq2 = true
humidity_min = "22"
color_format = "3"
date_format = "2"
time_format = "3"
enable_led = "false"
enable_buzzer = "false"
notification = "off"
email = "myemail@yahoo.org"
